# railway.toml
project = "womentaxi-laravel"
service = "web"

[build]
  # Commands to install dependencies and build your app
  install = ["composer install --no-interaction --optimize-autoloader"]
  build = []

[deploy]
  # Command to run migrations and clear cache on each deployment
  start = [
    "php artisan migrate --force",
    "php artisan config:clear",
    "php artisan cache:clear",
    "php artisan route:cache",
    "php artisan serve --host=0.0.0.0 --port=$PORT"
  ]

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:c5WiXFDnYQjmqWcZYTOgb5eiwSLClFn/gxawGcIVWxk="
APP_URL = "https://your-laravel-app.up.railway.app"

DB_CONNECTION = "mysql"
DB_HOST = "gondola.proxy.rlwy.net"
DB_PORT = "47771"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "dddifNVXvmDfIiVsWkkEamJCqjHVnFas"

SESSION_DRIVER = "cookie"
QUEUE_CONNECTION = "sync"
CACHE_DRIVER = "file"

CORS_ALLOW_ORIGIN = "*"
